<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: router.proto

namespace NetsvrBusiness\Router\Proto\GPBMetadata;

class Router
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
œ
router.protonetsvrBusiness.router"#
Router
cmd (
data (BHÊNetsvrBusiness\\Router\\Protoâ\'NetsvrBusiness\\Router\\Proto\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

